#!/bin/bash

adb kill-server
adb start-server
adb root
adb remount
adb push $PORT_ROOT/tools/filesysteminfo/getfilesysteminfo /system/xbin
adb shell getfilesysteminfo /system > tmp.txt
more tmp.txt | sort > filesysteminfo.txt
rm tmp.txt
